export const DepartmentData = [
  {department: '의예과·의학과', id: 1},
  {department: '간호학과', id: 2},
  {department: '국제어문학부', id: 3},
  {department: '인문문화학부', id: 4},
  {department: '공공인재학부', id: 5},
  {department: '미디어커뮤니케이션학과', id: 6},
  {department: '보건행정학과', id: 7},
  {department: '사회복지학과', id: 8},
  {department: '상담심리치료학과', id: 9},
  {department: '스포츠헬스케어학과', id: 10},
  {department: '유아교육과', id: 11},
  {department: '소비자·가족학과', id: 12},
  {department: '특수교육과', id: 13},
  {department: '경영학과', id: 14},
  {department: '경제통상학과', id: 15},
  {department: '경영학부', id: 16},
  {department: '국제경상학부', id: 17},
  {department: '건축학과', id: 18},
  {department: '디자인엔지니어링학과', id: 19},
  {department: '멀티미디어학부', id: 20},
  {department: '미래에너지공학과', id: 21},
  {department: '컴퓨터공학과', id: 22},
  {department: '실내디자인학과', id: 23},
];
